"""
Loads the cleaned data into PostgreSQL.

Reads the CSVs generated by tratar_dados.py and upserts them into the
database (dimensions, bridges and fact table), always through a staging
table + INSERT ... ON CONFLICT. Nothing here uses TRUNCATE: a TRUNCATE
CASCADE on dim_anime would drag fato_anime_metricas along with it (it has an
FK to dim_anime), wiping out the history from previous collection runs —
exactly what this script exists to preserve. Running it again with a new
collection appends history to the fact table and updates the
dimensions/bridges without losing anything.
"""

from pathlib import Path

import pandas as pd
from dotenv import dotenv_values
from sqlalchemy import create_engine, text

PASTA_PROCESSED = Path("data/processed")

# (table name, primary key columns, columns to update on conflict, date columns)
# `parse_dates` matters here: without it, date columns become text in the
# staging table and the INSERT ... SELECT tries to push text straight into a
# DATE column, which Postgres won't convert implicitly.
TABELAS = [
    ("dim_anime", ["anime_id"], [
        "titulo", "titulo_ingles", "titulo_japones", "tipo", "fonte", "episodios",
        "status", "em_exibicao", "data_inicio_exibicao", "data_fim_exibicao",
        "duracao_min", "ano", "temporada",
    ], ["data_inicio_exibicao", "data_fim_exibicao"]),
    ("dim_genero", ["nome_genero"], [], []),
    ("dim_estudio", ["estudio_id"], ["nome_estudio"], []),
    ("ponte_anime_genero", ["anime_id", "nome_genero"], [], []),
    ("ponte_anime_estudio", ["anime_id", "estudio_id"], [], []),
    ("fato_anime_metricas", ["anime_id", "data_coleta"], [
        "score", "scored_by", "rank", "popularity", "members", "favorites",
    ], ["data_coleta"]),
]


def carregar_engine():
    config = dotenv_values(".env")
    return create_engine(config["DATABASE_URL"])


def upsert_tabela(engine, nome, chave, colunas_update, colunas_data):
    caminho = PASTA_PROCESSED / f"{nome}.csv"
    df = pd.read_csv(caminho, parse_dates=colunas_data or None)
    staging = f"stg_{nome}"

    with engine.begin() as conn:
        df.to_sql(staging, conn, if_exists="replace", index=False, method="multi", chunksize=500)

        colunas = list(df.columns)
        colunas_sql = ", ".join(colunas)
        chave_sql = ", ".join(chave)

        if colunas_update:
            set_sql = ", ".join(f"{c} = EXCLUDED.{c}" for c in colunas_update)
            conflito_sql = f"ON CONFLICT ({chave_sql}) DO UPDATE SET {set_sql}"
        else:
            conflito_sql = f"ON CONFLICT ({chave_sql}) DO NOTHING"

        conn.execute(text(f"""
            INSERT INTO {nome} ({colunas_sql})
            SELECT {colunas_sql} FROM {staging}
            {conflito_sql}
        """))
        conn.execute(text(f"DROP TABLE {staging}"))

    return len(df)


def main():
    engine = carregar_engine()

    for nome, chave, colunas_update, colunas_data in TABELAS:
        qtd = upsert_tabela(engine, nome, chave, colunas_update, colunas_data)
        print(f"  {nome}: {qtd} linhas processadas (upsert)")

    print("\nValidando contagens no banco...")
    with engine.connect() as conn:
        for nome, _, _, _ in TABELAS:
            resultado = conn.execute(text(f"SELECT COUNT(*) FROM {nome}")).scalar()
            print(f"  {nome}: {resultado} linhas no banco")


if __name__ == "__main__":
    main()
